# Generated by Django 4.1.7 on 2023-04-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_guest', '0002_cart_category_delivery_dish_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
