# Generated by Django 4.2.1 on 2023-06-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering_guest', '0006_alter_category_image_alter_dish_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
        migrations.AlterModelTable(
            name='items',
            table='item',
        ),
    ]
